/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const HydrationEntry = IDL.Record({
  'glasses' : IDL.Nat,
  'date' : IDL.Text,
});
export const StepEntry = IDL.Record({ 'date' : IDL.Text, 'steps' : IDL.Nat });
export const WellbeingEntry = IDL.Record({
  'date' : IDL.Text,
  'energyScore' : IDL.Nat,
  'moodScore' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHydrationGoal' : IDL.Func([], [IDL.Nat], ['query']),
  'getLast7DaysHydration' : IDL.Func([], [IDL.Vec(HydrationEntry)], ['query']),
  'getLast7DaysSteps' : IDL.Func([], [IDL.Vec(StepEntry)], ['query']),
  'getLast7DaysWellbeing' : IDL.Func([], [IDL.Vec(WellbeingEntry)], ['query']),
  'getStepGoal' : IDL.Func([], [IDL.Nat], ['query']),
  'getTodayHydration' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getTodaySteps' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getTodayWellbeing' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(WellbeingEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logHydration' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'logSteps' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'logWellbeing' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setHydrationGoal' : IDL.Func([IDL.Nat], [], []),
  'setStepGoal' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const HydrationEntry = IDL.Record({ 'glasses' : IDL.Nat, 'date' : IDL.Text });
  const StepEntry = IDL.Record({ 'date' : IDL.Text, 'steps' : IDL.Nat });
  const WellbeingEntry = IDL.Record({
    'date' : IDL.Text,
    'energyScore' : IDL.Nat,
    'moodScore' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHydrationGoal' : IDL.Func([], [IDL.Nat], ['query']),
    'getLast7DaysHydration' : IDL.Func(
        [],
        [IDL.Vec(HydrationEntry)],
        ['query'],
      ),
    'getLast7DaysSteps' : IDL.Func([], [IDL.Vec(StepEntry)], ['query']),
    'getLast7DaysWellbeing' : IDL.Func(
        [],
        [IDL.Vec(WellbeingEntry)],
        ['query'],
      ),
    'getStepGoal' : IDL.Func([], [IDL.Nat], ['query']),
    'getTodayHydration' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getTodaySteps' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getTodayWellbeing' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WellbeingEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logHydration' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'logSteps' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'logWellbeing' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setHydrationGoal' : IDL.Func([IDL.Nat], [], []),
    'setStepGoal' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };