/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HydrationEntry { 'glasses' : bigint, 'date' : string }
export interface StepEntry { 'date' : string, 'steps' : bigint }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WellbeingEntry {
  'date' : string,
  'energyScore' : bigint,
  'moodScore' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHydrationGoal' : ActorMethod<[], bigint>,
  'getLast7DaysHydration' : ActorMethod<[], Array<HydrationEntry>>,
  'getLast7DaysSteps' : ActorMethod<[], Array<StepEntry>>,
  'getLast7DaysWellbeing' : ActorMethod<[], Array<WellbeingEntry>>,
  'getStepGoal' : ActorMethod<[], bigint>,
  'getTodayHydration' : ActorMethod<[string], bigint>,
  'getTodaySteps' : ActorMethod<[string], bigint>,
  'getTodayWellbeing' : ActorMethod<[string], [] | [WellbeingEntry]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logHydration' : ActorMethod<[string, bigint], undefined>,
  'logSteps' : ActorMethod<[string, bigint], undefined>,
  'logWellbeing' : ActorMethod<[string, bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setHydrationGoal' : ActorMethod<[bigint], undefined>,
  'setStepGoal' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];